/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VeChungToiRouteImport } from './routes/ve-chung-toi'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VeChungToiRoute = VeChungToiRouteImport.update({
  id: '/ve-chung-toi',
  path: '/ve-chung-toi',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ve-chung-toi': typeof VeChungToiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ve-chung-toi': typeof VeChungToiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ve-chung-toi': typeof VeChungToiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ve-chung-toi'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ve-chung-toi'
  id: '__root__' | '/' | '/ve-chung-toi'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  VeChungToiRoute: typeof VeChungToiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ve-chung-toi': {
      id: '/ve-chung-toi'
      path: '/ve-chung-toi'
      fullPath: '/ve-chung-toi'
      preLoaderRoute: typeof VeChungToiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VeChungToiRoute: VeChungToiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
