/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChuongTrinhRouteImport } from './routes/chuong-trinh'
import { Route as GiaSuRouteImport } from './routes/gia-su'
import { Route as KetQuaRouteImport } from './routes/ket-qua'
import { Route as LienHeRouteImport } from './routes/lien-he'
import { Route as MentorsRouteImport } from './routes/mentors'
import { Route as ThuVienRouteImport } from './routes/thu-vien'
import { Route as VeChungToiRouteImport } from './routes/ve-chung-toi'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChuongTrinhRoute = ChuongTrinhRouteImport.update({
  id: '/chuong-trinh',
  path: '/chuong-trinh',
  getParentRoute: () => rootRouteImport,
} as any)
const GiaSuRoute = GiaSuRouteImport.update({
  id: '/gia-su',
  path: '/gia-su',
  getParentRoute: () => rootRouteImport,
} as any)
const KetQuaRoute = KetQuaRouteImport.update({
  id: '/ket-qua',
  path: '/ket-qua',
  getParentRoute: () => rootRouteImport,
} as any)
const LienHeRoute = LienHeRouteImport.update({
  id: '/lien-he',
  path: '/lien-he',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorsRoute = MentorsRouteImport.update({
  id: '/mentors',
  path: '/mentors',
  getParentRoute: () => rootRouteImport,
} as any)
const ThuVienRoute = ThuVienRouteImport.update({
  id: '/thu-vien',
  path: '/thu-vien',
  getParentRoute: () => rootRouteImport,
} as any)
const VeChungToiRoute = VeChungToiRouteImport.update({
  id: '/ve-chung-toi',
  path: '/ve-chung-toi',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chuong-trinh': typeof ChuongTrinhRoute
  '/gia-su': typeof GiaSuRoute
  '/ket-qua': typeof KetQuaRoute
  '/lien-he': typeof LienHeRoute
  '/mentors': typeof MentorsRoute
  '/thu-vien': typeof ThuVienRoute
  '/ve-chung-toi': typeof VeChungToiRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chuong-trinh': typeof ChuongTrinhRoute
  '/gia-su': typeof GiaSuRoute
  '/ket-qua': typeof KetQuaRoute
  '/lien-he': typeof LienHeRoute
  '/mentors': typeof MentorsRoute
  '/thu-vien': typeof ThuVienRoute
  '/ve-chung-toi': typeof VeChungToiRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chuong-trinh': typeof ChuongTrinhRoute
  '/gia-su': typeof GiaSuRoute
  '/ket-qua': typeof KetQuaRoute
  '/lien-he': typeof LienHeRoute
  '/mentors': typeof MentorsRoute
  '/thu-vien': typeof ThuVienRoute
  '/ve-chung-toi': typeof VeChungToiRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chuong-trinh'
    | '/gia-su'
    | '/ket-qua'
    | '/lien-he'
    | '/mentors'
    | '/thu-vien'
    | '/ve-chung-toi'
    | '/admin/login'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chuong-trinh'
    | '/gia-su'
    | '/ket-qua'
    | '/lien-he'
    | '/mentors'
    | '/thu-vien'
    | '/ve-chung-toi'
    | '/admin/login'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/chuong-trinh'
    | '/gia-su'
    | '/ket-qua'
    | '/lien-he'
    | '/mentors'
    | '/thu-vien'
    | '/ve-chung-toi'
    | '/admin/login'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChuongTrinhRoute: typeof ChuongTrinhRoute
  GiaSuRoute: typeof GiaSuRoute
  KetQuaRoute: typeof KetQuaRoute
  LienHeRoute: typeof LienHeRoute
  MentorsRoute: typeof MentorsRoute
  ThuVienRoute: typeof ThuVienRoute
  VeChungToiRoute: typeof VeChungToiRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chuong-trinh': {
      id: '/chuong-trinh'
      path: '/chuong-trinh'
      fullPath: '/chuong-trinh'
      preLoaderRoute: typeof ChuongTrinhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gia-su': {
      id: '/gia-su'
      path: '/gia-su'
      fullPath: '/gia-su'
      preLoaderRoute: typeof GiaSuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ket-qua': {
      id: '/ket-qua'
      path: '/ket-qua'
      fullPath: '/ket-qua'
      preLoaderRoute: typeof KetQuaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lien-he': {
      id: '/lien-he'
      path: '/lien-he'
      fullPath: '/lien-he'
      preLoaderRoute: typeof LienHeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentors': {
      id: '/mentors'
      path: '/mentors'
      fullPath: '/mentors'
      preLoaderRoute: typeof MentorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thu-vien': {
      id: '/thu-vien'
      path: '/thu-vien'
      fullPath: '/thu-vien'
      preLoaderRoute: typeof ThuVienRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ve-chung-toi': {
      id: '/ve-chung-toi'
      path: '/ve-chung-toi'
      fullPath: '/ve-chung-toi'
      preLoaderRoute: typeof VeChungToiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChuongTrinhRoute: ChuongTrinhRoute,
  GiaSuRoute: GiaSuRoute,
  KetQuaRoute: KetQuaRoute,
  LienHeRoute: LienHeRoute,
  MentorsRoute: MentorsRoute,
  ThuVienRoute: ThuVienRoute,
  VeChungToiRoute: VeChungToiRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
